### PR TITLE
Mac target localhost container via gemini openai proxy

### PR DESCRIPTION
**Pull request by lloydchang**

### CODE REVIEW

**Comment by lloydchang** [comment]
Relates to Implement additional gemini backend https://github.com/ipa-lab/hackingBuddyGPT/issues/84

**Comment by andreashappe** [comment]
I will merge this for now.. would it be possible to move some of the shell-script functions into a common shellscript and include this from the different scripts (similar to a library)?

**Review by andreashappe — APPROVED** [review]

**Comment by lloydchang** [comment]
**Update:** As an experiment, I used Cline (AI Agent) and Gemini (LLM) with the following prompt:  
> would it be possible to move some of the shell-script functions into a common shellscript and include this from the different scripts (similar to a library)?

Cline and Gemini refactored by creating a new file, `common_function.sh` while editing existing files.

I tried running the output on Codespaces and Mac, but I encountered compatibility issues due to conflicting syntax and different *nix utilities between the two operating systems, Ubuntu Linux versus macOS.

To mitigate that, I tried to add conditional statements to differentiate Linux versus Mac in `common_function.sh`.

* Ironically, adding conditionals undermines the purpose of naming the file `common_functions.sh` in the first place.

* Thus, I don't think `common_functions.sh` is worth the return on investment nor additional time required to try refactoring.

--

**Visibility:**

If the concern is about too many files in root directory, perhaps existing files are movable into sub-directories to differentiate between Codespaces versus Mac.

--

**Clarification:**

Within each environment—Codespaces or Mac—there are two shell scripts because there are two different entry points:

1. Start containers at initialization:

    * `create_and_start_containers`

versus

2. Start hackingBuddyGPT, the app, at run-time:

    * `start_hackingbuddygpt`

**Comment by andreashappe** [comment]
yes, moving those scripts, e.g., into `/scripts` might improve readability.. could you do that?

Using different bash/zsh versions: yes, this is a problem (but this is already a problem now too.. shouldn't we include sanity checks in the different scripts that the expected bash version is the currently used version?

**Comment by lloydchang** [comment]
yes and yes at https://github.com/ipa-lab/hackingBuddyGPT/pull/96

**Pull request merged**
